CATALOGUE_HOST: catalogue.devsecopstrainee.site
USER_HOST: user.devsecopstrainee.site
CART_HOST: cart.devsecopstrainee.site
SHIPPING_HOST: shipping.devsecopstrainee.site
PAYMENT_HOST: payment.devsecopstrainee.site