  - name: app_setup
    include_role:
      name: common
      tasks_from: app-setup

  - name: python_setup
    include_role:
      name: common
      tasks_from: python-setup

  - name: systemdSetup
    include_role:
      name: common
      tasks_from: systemd-setup