  - name: disabling default nginx
    ansible.builtin.command:  dnf module disable nginx -y

  - name: enabling nginx:1.24
    ansible.builtin.command:  dnf module enable nginx:1.24 -y

  - name:  installing nginx
    ansible.builtin.dnf:
      name: nginx
      state:  present
    
  - name: start and enabling nginx
    ansible.builtin.service:
      name: nginx
      state:  started
      enabled:  yes 

  - name: remooving default content of nginx
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: creating html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: downloading the service
    ansible.builtin.get_url:
      url:  https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: unzip frontend code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes
  
  - name: removing default nginx configuration
    ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      state: absent

  - name: copying nginx configuration
    ansible.builtin.template: #It will take form from the template
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    notify: # notify will check in handlers
      - Restart nginx # After any changes made in configuration then by using notify tag we will cal handlers.
      # In handlers the tag which is having the name "Restart nginx" it will going to execute.


  