- name: stop the server
  ansible.builtin.service:
    name: "{{ component }}"
    state: stopped

- name: removing old code
  ansible.builtin.file:
    path: /app
    state: absent

-  name: creating new direcoty
   ansible.builtin.file:
    path: /app
    state: directory

- name: downloading the new code
  ansible.builtin.unarchive: #By using this module we can download and unzip at a time
    src: "https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v{{ app_version }}.zip"
    dest: /app
    remote_src: yes

- name: install dependencies
  community.general.npm:
    path: /app

- name: restart the service
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted

