  - name: copying "{{ component }}" service
    ansible.builtin.template: # previously it is ansible.builtin.copy but here we are taking it from template so we change to template
      src: "{{ component}}.service.j2"
      dest: "/etc/systemd/system/{{ component }}.service"
      #If you give "{{ component }}" then file will save along with "", so that it will not able take restart.

  - name:  Taking daemon reload
    ansible.builtin.systemd_service:
      daemon_reload:  yes

  - name: start and enabling {{ component }}
    ansible.builtin.service:
      name: "{{ component }}"
      state:  restarted #even app is not running we can restart the application
      enabled:  yes
